name             'elastic'
maintainer       'Mojzis Stupka'
maintainer_email 'mojzisek@gmail.com'
license          'All rights reserved'
description      'Elastic search'
long_description 'Elastic search'
version          '0.1.0'

depends 'apt'
depends 'simple-chef-tools'